"""
Django settings for dealercore project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
import sys
from datetime import timedelta
env = environ.Env(SB_DEBUG=(bool, False))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR.parent, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

# FIX S-5: SECRET_KEY must come from environment in production.
# In development (DEBUG=True) we fall back to an insecure default so local
# setup keeps working without a .env file, but a loud warning is logged.
# In production, a missing SECRET_KEY causes startup to fail.
_RAW_SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") or os.getenv("SECRET_KEY")
if _RAW_SECRET_KEY:
    SECRET_KEY = _RAW_SECRET_KEY
elif DEBUG:
    import warnings
    warnings.warn(
        "DJANGO_SECRET_KEY is not set — using an insecure development "
        "default. NEVER deploy with this default. Set DJANGO_SECRET_KEY "
        "in your environment or .env file.",
        RuntimeWarning,
    )
    SECRET_KEY = 'django-insecure-=3$*v73(-9%a#8$*ba7$spzzk4$!zqqq75vm)7y12%jtjpc_q4'
else:
    raise RuntimeError(
        "DJANGO_SECRET_KEY environment variable is required when "
        "DEBUG=False. Refusing to start with an insecure default."
    )

# FIX L-4: restrict ALLOWED_HOSTS by default. In production, set
# DJANGO_ALLOWED_HOSTS to a comma-separated list. In DEBUG we keep the
# permissive default for local development.
ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=["*"] if DEBUG else [],
)


# Application definition

INSTALLED_APPS = [
    "daphne", 
    "admin_interface",
    "colorfield",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "channels",
    "django_celery_results",
    "django_celery_beat",
    "corsheaders",
    "ninja_extra",
    "ninja_jwt",
    "ninja_jwt.token_blacklist",
    
    # DEALERCORE apps
    "inventory",
    "sales",
    "dsr",
    "supplier",
    "dealer",
    "reports",
    "users",
]
SILENCED_SYSTEM_CHECKS = ["security.W019"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'common.permission_middleware.PermissionMiddleware',  # Extract role from JWT
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-service-domain",
    "x-api-key",
    "x-dealer-username",  # Multi-tenancy header for DSR context
]
CORS_EXPOSE_HEADERS = [
    "x-api-key",
    "x-service-domain",
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = env.list(
    "SL_CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:4323",
        "http://localhost:8088",
        "http://127.0.0.1:4323",
        "http://127.0.0.1:8088",
        "http://localhost:4321",
        "http://127.0.0.1:4321",
        "http://localhost:4323"
    ],
)

CSRF_TRUSTED_ORIGINS = env.list(
    "SL_CSRF_TRUSTED_ORIGINS",
    default=[
        "http://localhost:4322",
        "http://localhost:8087",
        "http://127.0.0.1:4322",
        "http://127.0.0.1:8087",
        "http://127.0.0.1:8000",
        "http://127.0.0.1:4321",
        "http://localhost:4323"
    ],
)

ROOT_URLCONF = 'dealercore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dealercore.wsgi.application'
ASGI_APPLICATION = 'dealercore.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'dealer_db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model for DealerBackend
# DSRs and dealer staff have separate accounts from SattaBase users
AUTH_USER_MODEL = 'users.DsrUser'

# =============================================================================
# SATTABASE INTEGRATION SETTINGS
# =============================================================================
# NOTE: Dealer authentication goes directly from the frontend to SattaBase
# (login, refresh, /billing/auth/me, /auth/authorize). The legacy
# sattabase_client.py + AuthController/SSOController/AccessController proxy
# layer was removed; there are no remaining server-to-server flows that
# require backend-to-SattaBase HTTP. JWT verification is now done locally
# by PermissionMiddleware using the keys below.

# JWT Configuration (must match SattaBase)
# Access token lifetime for token validation
JWT_ACCESS_TOKEN_LIFETIME = timedelta(minutes=60)


# SattaBase JWT verification (FIX S-1, Audit A1).
# The PermissionMiddleware verifies SattaBase-issued JWTs.
#
# Two verification modes are supported:
#
# 1. RS256 (production, recommended): Set SATTABASE_JWT_PUBLIC_KEY to the
#    PEM-encoded public key. Asymmetric crypto ensures a DealerBackend
#    compromise cannot be used to forge SattaBase JWTs for other sister
#    domains.
#
# 2. HS256 (dev only): Set SATTABASE_JWT_SHARED_SECRET to SattaBase's
#    JWT signing key (same value as SB_JWT_SIGNING_KEY in SattaBase .env).
#    This is simpler for dev but is a security anti-pattern in production
#    (a DealerBackend compromise would let an attacker forge tokens for
#    ALL sister domains).
#
# If neither key is configured, SattaBase JWT verification decodes WITHOUT
# signature verification (DEBUG=True only — fails closed in production).
#
# Env var compatibility: both SATTABASE_JWT_* and SB_JWT_* prefixes are
# accepted. The .env.example uses SB_ prefix; some deployments use
# SATTABASE_ prefix. We try both.

# JWT algorithm — HS256 for dev (shared secret), RS256 for prod (public key)
SATTABASE_JWT_ALGORITHM = os.getenv(
    "SATTABASE_JWT_ALGORITHM",
    os.getenv("SB_JWT_ALGORITHM", "RS256"),
)

# HS256 shared secret (dev only — same as SattaBase's SB_JWT_SIGNING_KEY)
SATTABASE_JWT_SHARED_SECRET = os.getenv(
    "SATTABASE_JWT_SHARED_SECRET",
    os.getenv("SB_JWT_SIGNING_KEY", os.getenv("SB_JWT_SHARED_SECRET", "")),
)

# RS256 public key (production)
SATTABASE_JWT_PUBLIC_KEY = os.getenv(
    "SATTABASE_JWT_PUBLIC_KEY",
    os.getenv("SB_JWT_PUBLIC_KEY", ""),
)

# Issuer and audience validation - leave empty if SattaBase JWT doesn't include these claims
SATTABASE_JWT_ISSUER = os.getenv(
    "SATTABASE_JWT_ISSUER",
    os.getenv("SB_JWT_ISSUER", ""),
)
SATTABASE_JWT_AUDIENCE = os.getenv(
    "SATTABASE_JWT_AUDIENCE",
    os.getenv("SB_JWT_AUDIENCE", ""),
)




# =============================================================================
# SATTABASE ACCESS CLIENT SETTINGS
# =============================================================================
# Used by common/sattabase_access.py to query the SattaBase subscriber-access
# endpoint. This is the server-to-server channel that lets DealerBackend
# discover what the dealer's subscription plan allows, so DSR permissions can
# be constrained accordingly.

# Base URL of the SattaBase backend (no trailing slash)
# Env var compat: .env.example uses SB_API_BASE_URL, some deployments use SATTABASE_API_BASE_URL
SATTABASE_API_BASE_URL = os.getenv(
    "SATTABASE_API_BASE_URL",
    os.getenv("SB_API_BASE_URL", "http://localhost:8086/api/v1"),
)
# dealercore's API key for authenticating to SattaBase. This is a "ServiceCredential"
# API key issued by SattaBase for this sister domain's ServiceDomain.
# Required in production — the /billing/service/subscriber/access endpoint
# uses IsServiceAuthenticated which validates the X-API-Key header.
#
# Named SATTABASE_API_KEY_FOR_DEALER because each sister domain gets its
# OWN API key. Future sister domains will have their own keys
# (SATTABASE_API_KEY_FOR_INVENTORY, etc.). We also accept the legacy
# SATTABASE_API_KEY and SB_API_KEY names for backwards compatibility.
SATTABASE_API_KEY = (
    os.getenv("SATTABASE_API_KEY_FOR_DEALER")
    or os.getenv("SATTABASE_API_KEY")
    or os.getenv("SB_API_KEY")
    or ""
)


# The service domain slug that identifies this product in SattaBase's
# ServiceDomain table. Must match the `domain` field exactly.
# Env var compat: .env.example uses SB_SERVICE_DOMAIN
SATTABASE_SERVICE_DOMAIN = os.getenv(
    "SATTABASE_SERVICE_DOMAIN",
    os.getenv("SB_SERVICE_DOMAIN", "localhost:4323"),
)

# Cache TTL (seconds) for dealer access lookups. 5 minutes balances
# freshness (plan changes propagate quickly) against SattaBase load.
SATTABASE_ACCESS_CACHE_TTL = int(os.getenv("SATTABASE_ACCESS_CACHE_TTL", "300"))

# GAP E-4 fix: strict mode controls what happens when SattaBase is
# unreachable (network error, missing API key, 404 on subscriber).
#
# False (default, dev-friendly): permissive fallback — empty access map,
# which means missing keys are treated as "allowed". This keeps the dev
# environment working without a running SattaBase, but is a security
# risk in production (a SattaBase outage disables ALL plan-level
# enforcement).
#
# True (production): restrictive fallback — all gated modules denied.
# This is the safe default for production. Set via env var so it can
# be toggled without code changes.
#
# In production, set SATTABASE_ACCESS_STRICT_MODE=True in the .env file.
SATTABASE_ACCESS_STRICT_MODE = os.getenv(
    "SATTABASE_ACCESS_STRICT_MODE", "false"
).lower() in ("true", "1", "yes", "on")




# =============================================================================
# DSR AUTHENTICATION SETTINGS
# =============================================================================
# Settings for DSR login and JWT token generation

# JWT settings for DSR authentication
NINJA_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'USER_AUTHENTICATION_RULE': 'ninja_jwt.authentication.default_user_authentication_rule',
}

# Invitation settings
DSR_INVITATION_EXPIRY_DAYS = 7
DSR_PASSWORD_RESET_EXPIRY_HOURS = 24


# =============================================================================
# CELERY CONFIGURATION
# =============================================================================
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = "django-db"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@dealercore.local")

# DealerFrontend URL for invitation links
DEALER_FRONTEND_URL = os.getenv("DEALER_FRONTEND_URL", "http://localhost:4323")

# Site name for emails
SITE_NAME = os.getenv("SITE_NAME", "DealerCore")



