"""
Django settings for dealercore project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
import sys
from datetime import timedelta
env = environ.Env(SB_DEBUG=(bool, False))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR.parent, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=3$*v73(-9%a#8$*ba7$spzzk4$!zqqq75vm)7y12%jtjpc_q4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "daphne", 
    "admin_interface",
    "colorfield",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "channels",
    "django_celery_results",
    "django_celery_beat",
    "corsheaders",
    "ninja_extra",
    "ninja_jwt",
    "ninja_jwt.token_blacklist",
    
    # DEALERCORE apps
    "inventory",
    "sales",
    "dsr",
    "supplier",
    "dealer",
    "reports",
    "users",
]
SILENCED_SYSTEM_CHECKS = ["security.W019"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'common.permission_middleware.PermissionMiddleware',  # Extract role from JWT
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-service-domain",
    "x-api-key",
    "x-dealer-username",  # Multi-tenancy header for DSR context
]
CORS_EXPOSE_HEADERS = [
    "x-api-key",
    "x-service-domain",
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = env.list(
    "SL_CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:4323",
        "http://localhost:8088",
        "http://127.0.0.1:4323",
        "http://127.0.0.1:8088",
        "http://localhost:4321",
        "http://127.0.0.1:4321",
        "http://localhost:4323"
    ],
)

CSRF_TRUSTED_ORIGINS = env.list(
    "SL_CSRF_TRUSTED_ORIGINS",
    default=[
        "http://localhost:4322",
        "http://localhost:8087",
        "http://127.0.0.1:4322",
        "http://127.0.0.1:8087",
        "http://127.0.0.1:8000",
        "http://127.0.0.1:4321",
        "http://localhost:4323"
    ],
)

ROOT_URLCONF = 'dealercore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dealercore.wsgi.application'
ASGI_APPLICATION = 'dealercore.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'dealer_db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model for DealerBackend
# DSRs and dealer staff have separate accounts from SattaBase users
AUTH_USER_MODEL = 'users.DsrUser'

# =============================================================================
# SATTABASE INTEGRATION SETTINGS
# =============================================================================
# Configuration for connecting to SattaBase central authentication system.
# The frontend calls SattaBase directly for auth; these settings are for
# server-to-server calls (e.g., token validation, webhook processing).

# SattaBase Backend API URL
SATTABASE_API_URL = os.getenv("SB_API_BASE_URL", "http://localhost:8086/api/v1")

# Service Domain identifier - must match ServiceDomain in SattaBase
SATTABASE_SERVICE_DOMAIN = os.getenv("SB_SERVICE_DOMAIN", "localhost:4323")

# API Key for server-to-server calls (from SattaBase admin)
SATTABASE_API_KEY = os.getenv("SB_API_KEY", "")

# SattaBase Frontend URL (for redirects, email links)
SATTABASE_FRONTEND_URL = os.getenv("SB_FRONTEND_URL", "http://localhost:4321")

# JWT Configuration (must match SattaBase)
# Access token lifetime for token validation
JWT_ACCESS_TOKEN_LIFETIME = timedelta(minutes=60)



# =============================================================================
# DSR AUTHENTICATION SETTINGS
# =============================================================================
# Settings for DSR login and JWT token generation

# JWT settings for DSR authentication
NINJA_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'USER_AUTHENTICATION_RULE': 'ninja_jwt.authentication.default_user_authentication_rule',
}

# Invitation settings
DSR_INVITATION_EXPIRY_DAYS = 7
DSR_PASSWORD_RESET_EXPIRY_HOURS = 24

