# Generated by Django 5.2.13 on 2026-06-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['category'], name='supplier_su_categor_0c8ff2_idx'),
        ),
    ]
