# Generated by Django 5.2.13 on 2026-06-11 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_dealerconfig_address_dealerconfig_business_name_and_more'),
        ('supplier', '0002_supplier_supplier_su_categor_0c8ff2_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='dealer',
            field=models.ForeignKey(db_column='dealer_username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='dealer.dealerconfig'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['dealer', 'name'], name='supplier_su_dealer__4d923e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['dealer', 'category'], name='supplier_su_dealer__1d7021_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('name', 'dealer'), name='unique_supplier_per_dealer'),
        ),
    ]
