# Generated by Django 5.2.13 on 2026-06-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_brand_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock', 'min_stock_alert'], name='inventory_p_stock_ab308e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'category'], name='inventory_p_brand_81a099_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='inventory_p_sku_f85905_idx'),
        ),
        migrations.AddIndex(
            model_name='restockrecord',
            index=models.Index(fields=['product', '-date'], name='inventory_r_product_465696_idx'),
        ),
        migrations.AddIndex(
            model_name='restockrecord',
            index=models.Index(fields=['supplier_name', '-date'], name='inventory_r_supplie_a4a5b1_idx'),
        ),
    ]
