# Generated by Django 5.2.13 on 2026-06-11 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_dealerconfig_address_dealerconfig_business_name_and_more'),
        ('inventory', '0003_product_inventory_p_stock_ab308e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='dealer',
            field=models.ForeignKey(db_column='dealer_username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='dealer.dealerconfig'),
        ),
        migrations.AddField(
            model_name='category',
            name='dealer',
            field=models.ForeignKey(db_column='dealer_username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dealer.dealerconfig'),
        ),
        migrations.AddField(
            model_name='product',
            name='dealer',
            field=models.ForeignKey(db_column='dealer_username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dealer.dealerconfig'),
        ),
        migrations.AddField(
            model_name='restockrecord',
            name='dealer',
            field=models.ForeignKey(db_column='dealer_username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='dealer.dealerconfig'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['dealer', 'name'], name='inventory_b_dealer__d356fc_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['dealer', 'name'], name='inventory_c_dealer__1e6238_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['dealer', 'name'], name='inventory_p_dealer__038e43_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['dealer', 'category'], name='inventory_p_dealer__915d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='restockrecord',
            index=models.Index(fields=['dealer', '-date'], name='inventory_r_dealer__124751_idx'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('name', 'dealer'), name='unique_brand_per_dealer'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'dealer'), name='unique_category_per_dealer'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sku', 'dealer'), name='unique_sku_per_dealer'),
        ),
    ]
