# Generated by Django 5.2.13 on 2026-06-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_dealerconfig_address_dealerconfig_business_name_and_more'),
        ('inventory', '0004_brand_dealer_category_dealer_product_dealer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restockrecord',
            name='dealer',
            field=models.ForeignKey(db_column='dealer_username', on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='dealer.dealerconfig'),
        ),
    ]
