# Generated by Django 5.2.13 on 2026-06-12 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_dealerconfig_address_dealerconfig_business_name_and_more'),
        ('inventory', '0005_alter_restockrecord_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='dealer',
            field=models.ForeignKey(db_column='dealer_username', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='dealer.dealerconfig'),
        ),
    ]
