# Generated by Django 5.2.13 on 2026-04-27 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name, e.g. 'Satta Finance'", max_length=100, unique=True, verbose_name='Product Name')),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'finance'", unique=True, verbose_name='Slug')),
                ('domain', models.CharField(db_index=True, help_text="Service domain, e.g. 'finance.sattabase.tld'", max_length=255, unique=True, verbose_name='Service Domain')),
                ('description', models.TextField(blank=True, default='', help_text='Product description shown to users', verbose_name='Description')),
                ('icon', models.ImageField(blank=True, help_text='Product icon or logo', null=True, upload_to='products/%Y/%m/', verbose_name='Icon')),
                ('home_url', models.URLField(blank=True, default='', help_text='Landing page URL for this service', verbose_name='Home URL')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this product is accepting new signups', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'billing_product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Plan name, e.g. 'Free', 'Standard'", max_length=50, verbose_name='Plan Name')),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'standard'", verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', help_text='Plan description shown to users', verbose_name='Description')),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Price in cents (0 = free plan). 900 = $9.00', verbose_name='Price (cents)')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3, verbose_name='Currency')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], db_index=True, default='monthly', help_text='How often the user is billed', max_length=20, verbose_name='Billing Cycle')),
                ('trial_days', models.PositiveIntegerField(default=0, help_text='Free trial duration in days (0 = no trial)', verbose_name='Trial Days')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Public feature list for display (e.g. {"reports": "Advanced", "storage": "10GB"})', verbose_name='Public Features')),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID (null for free plans)', max_length=100, null=True, verbose_name='Stripe Price ID')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)', verbose_name='Sort Order')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this plan is available for new subscriptions', verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this plan in comparison UI', verbose_name='Featured')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='billing.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'billing_plan',
                'ordering': ['product', 'sort_order', 'price_cents'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('trialing', 'Trialing'), ('paused', 'Paused'), ('expired', 'Expired')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, help_text='Stripe Subscription ID for webhook correlation', max_length=100, null=True, unique=True, verbose_name='Stripe Subscription ID')),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, help_text='Stripe Customer ID for portal access', max_length=100, null=True, verbose_name='Stripe Customer ID')),
                ('current_period_start', models.DateTimeField(blank=True, help_text='Start of the current billing period', null=True, verbose_name='Period Start')),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, help_text='End of the current billing period', null=True, verbose_name='Period End')),
                ('trial_start', models.DateTimeField(blank=True, help_text='Start of the trial period', null=True, verbose_name='Trial Start')),
                ('trial_end', models.DateTimeField(blank=True, help_text='End of the trial period', null=True, verbose_name='Trial End')),
                ('canceled_at', models.DateTimeField(blank=True, help_text='When the user requested cancellation', null=True, verbose_name='Canceled At')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Hard expiration for lifetime plans', null=True, verbose_name='Expires At')),
                ('plan', models.ForeignKey(help_text='PROTECT prevents deleting plans with active subscribers', on_delete=django.db.models.deletion.PROTECT, to='billing.plan', verbose_name='Plan')),
                ('product', models.ForeignKey(help_text='Denormalized from plan.product for query speed', on_delete=django.db.models.deletion.CASCADE, to='billing.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'billing_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="Feature identifier, e.g. 'reports', 'max_accounts'", max_length=100, verbose_name='Access Key')),
                ('value', models.CharField(help_text="Access value, e.g. 'true', '5', '1000'", max_length=255, verbose_name='Access Value')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('boolean', 'Boolean'), ('integer', 'Integer')], default='string', help_text='Determines how the value is cast (string, boolean, integer)', max_length=10, verbose_name='Value Type')),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of this access entry', verbose_name='Description')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_entries', to='billing.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Access Entry',
                'verbose_name_plural': 'Access Entries',
                'db_table': 'billing_access_entry',
                'ordering': ['plan', 'key'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'key'), name='unique_access_key_per_plan')],
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('product', 'slug'), name='unique_plan_slug_per_product'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_subscription_per_user_product'),
        ),
    ]
