# Generated by Django 5.2.13 on 2026-04-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_product_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='has_used_trial',
            field=models.BooleanField(default=False, help_text='Set to True once the user has consumed a trial for this product. Prevents trial abuse via repeated plan cycling.', verbose_name='Has Used Trial'),
        ),
    ]
