# Generated by Django 5.2.13 on 2026-04-28 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_subscription_has_used_trial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tax_inclusive',
            field=models.BooleanField(db_index=True, default=False, help_text="Whether the displayed price already includes tax. If True, Stripe will use tax_behavior='inclusive'. If False, tax_behavior='exclusive' (tax added at checkout).", verbose_name='Tax Inclusive'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tos_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the user accepted the Terms of Service for this subscription', null=True, verbose_name='ToS Accepted At'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tos_version',
            field=models.CharField(blank=True, default='', help_text="Version of the Terms of Service the user accepted (e.g. '1.0')", max_length=20, verbose_name='ToS Version'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stripe_refund_id', models.CharField(blank=True, db_index=True, help_text='Stripe Refund ID (e.g. re_...)', max_length=100, null=True, unique=True, verbose_name='Stripe Refund ID')),
                ('stripe_charge_id', models.CharField(blank=True, default='', help_text='The Stripe Charge/PaymentIntent ID that was refunded', max_length=100, verbose_name='Stripe Charge ID')),
                ('amount_cents', models.PositiveIntegerField(help_text='Refund amount in cents (e.g. 900 = $9.00)', verbose_name='Amount (cents)')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3, verbose_name='Currency')),
                ('reason', models.CharField(blank=True, default='', help_text='Reason for the refund (visible to customer on their bank statement)', max_length=255, verbose_name='Reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('stripe_response', models.JSONField(blank=True, default=dict, help_text='Full Stripe Refund API response for audit', verbose_name='Stripe Response')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='Admin user who initiated this refund', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Initiated By')),
                ('subscription', models.ForeignKey(help_text='The subscription this refund is for', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='billing.subscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'billing_refund',
                'ordering': ['-created_at'],
            },
        ),
    ]
