# Generated by Django 5.2.13 on 2026-04-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_plan_tax_inclusive_subscription_tos_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(blank=True, db_index=True, default='', help_text="ISO 4217 currency code denormalized from the user's profile at checkout time. Used for frontend price display. Empty = fallback to plan.currency.", max_length=3, verbose_name='Billing Currency'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(db_index=True, default='USD', help_text='ISO 4217 code of the source currency (e.g. USD)', max_length=3, verbose_name='Base Currency')),
                ('target_currency', models.CharField(db_index=True, help_text='ISO 4217 code of the target currency (e.g. BDT)', max_length=3, verbose_name='Target Currency')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate: 1 unit of base_currency = ? units of target_currency', max_digits=18, verbose_name='Rate')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When this rate was last fetched from the API', verbose_name='Fetched At')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'db_table': 'billing_exchange_rate',
                'ordering': ['target_currency'],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'target_currency'), name='unique_exchange_rate_pair')],
            },
        ),
    ]
