# Generated by Django 5.2.13 on 2026-04-29 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_subscription_dunning_step_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Internal admin-only notes about this refund', verbose_name='Admin Notes'),
        ),
        migrations.AddField(
            model_name='refund',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this refund was approved', null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='refund',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this refund (if multi-step approval)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='refund',
            name='initiated_by_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the admin who initiated this refund', null=True, verbose_name='Initiated By IP'),
        ),
        migrations.AddField(
            model_name='refund',
            name='reason_category',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Structured reason code for audit trail: customer_request, billing_error, goodwill, policy, chargeback', max_length=30, verbose_name='Reason Category'),
        ),
        migrations.CreateModel(
            name='PlanChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('proration_amount_cents', models.IntegerField(help_text='Proration credit/charge amount in cents. Negative = credit to customer, Positive = charge.', verbose_name='Proration Amount (cents)')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3, verbose_name='Currency')),
                ('stripe_proration_id', models.CharField(blank=True, default='', help_text='ID of the Stripe proration line item', max_length=100, verbose_name='Stripe Proration ID')),
                ('proration_behavior', models.CharField(blank=True, default='create_prorations', help_text='How the proration was handled: create_prorations, none, or always_invoice', max_length=30, verbose_name='Proration Behavior')),
                ('from_plan', models.ForeignKey(help_text='The plan being changed from', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.plan', verbose_name='From Plan')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who initiated the plan change (null for system/webhook)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Initiated By')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_changes', to='billing.subscription', verbose_name='Subscription')),
                ('to_plan', models.ForeignKey(help_text='The plan being changed to', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.plan', verbose_name='To Plan')),
            ],
            options={
                'verbose_name': 'Plan Change Log',
                'verbose_name_plural': 'Plan Change Logs',
                'db_table': 'billing_plan_change_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
