# Generated by Django 5.2.13 on 2026-04-29 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_refund_admin_notes_refund_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueRecognitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('amount_cents', models.PositiveIntegerField(default=0, help_text='Revenue recognized in cents for this day', verbose_name='Amount (cents)')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3, verbose_name='Currency')),
                ('period_start', models.DateTimeField(blank=True, help_text='Start of the billing period this entry covers', null=True, verbose_name='Period Start')),
                ('period_end', models.DateTimeField(blank=True, help_text='End of the billing period this entry covers', null=True, verbose_name='Period End')),
                ('recognized_date', models.DateField(db_index=True, help_text='The date this revenue is recognized for', verbose_name='Recognized Date')),
                ('stripe_invoice_id', models.CharField(blank=True, db_index=True, default='', help_text='The Stripe invoice that generated this revenue', max_length=100, verbose_name='Stripe Invoice ID')),
                ('plan', models.ForeignKey(help_text='The plan at the time of recognition', on_delete=django.db.models.deletion.PROTECT, to='billing.plan', verbose_name='Plan')),
                ('subscription', models.ForeignKey(help_text='The subscription this revenue entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='revenue_entries', to='billing.subscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Revenue Recognition Entry',
                'verbose_name_plural': 'Revenue Recognition Entries',
                'db_table': 'billing_revenue_recognition',
                'ordering': ['-recognized_date'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'recognized_date'), name='unique_revenue_per_sub_per_day')],
            },
        ),
    ]
