# Generated by Django 5.2.13 on 2026-04-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_revenuerecognitionentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_fee_cents',
            field=models.PositiveIntegerField(default=0, help_text='Stripe processing fee for this invoice (2.9% + $0.30)', verbose_name='Stripe Fee (cents)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_fee_currency',
            field=models.CharField(blank=True, default='', help_text='Currency of the Stripe fee', max_length=3, verbose_name='Stripe Fee Currency'),
        ),
    ]
