# Generated by Django 5.2.13 on 2026-04-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoice_stripe_fee_cents_invoice_stripe_fee_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuerecognitionentry',
            name='source',
            field=models.CharField(blank=True, db_index=True, default='scheduled', help_text="How this entry was created: 'scheduled' (Celery daily task), 'webhook' (created immediately on payment), 'backfill' (manual)", max_length=30, verbose_name='Source'),
        ),
    ]
