# Generated by Django 5.2.13 on 2026-04-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_revenuerecognitionentry_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='past_due_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the subscription first transitioned to PAST_DUE. Used by the dunning workflow to calculate days_past_due accurately, since updated_at is modified by every save operation.', null=True, verbose_name='Past Due At'),
        ),
    ]
