# Generated by Django 5.2.13 on 2026-04-30 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_subscription_past_due_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'Finance Backend Production'", max_length=100, verbose_name='Credential Name')),
                ('api_key_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the API key (raw key never stored)', max_length=255, unique=True, verbose_name='API Key Hash')),
                ('api_key_prefix', models.CharField(db_index=True, help_text="First 12 chars for identification (e.g. 'sb_live_a1Bc')", max_length=12, verbose_name='API Key Prefix')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text="Scoped permissions: {'auth': True, 'billing_read': True}. Controls which API surface this credential can access.", verbose_name='Permissions')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Can be revoked instantly by setting to False', verbose_name='Active')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this credential was last used (audit)', null=True, verbose_name='Last Used At')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this credential', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('service_domain', models.OneToOneField(help_text='One credential per service domain', on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='billing.servicedomain', verbose_name='Service Domain')),
            ],
            options={
                'verbose_name': 'Service Credential',
                'verbose_name_plural': 'Service Credentials',
                'db_table': 'billing_service_credential',
                'ordering': ['-created_at'],
            },
        ),
    ]
