# Generated by Django 5.2.13 on 2026-04-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_servicecredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='True when the subscription is scheduled to cancel at the end of the current billing period. Set by Stripe when the user cancels from the portal or via the cancel API.', verbose_name='Cancel at Period End'),
        ),
    ]
