# Generated by Django 5.2.13 on 2026-05-03 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_invoicelineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text="Action identifier, e.g. 'product.create', 'plan.update', 'subscription.override', 'refund.approve'", max_length=100, verbose_name='Action')),
                ('method', models.CharField(blank=True, default='', help_text='HTTP method of the API call: GET, POST, PUT, PATCH, DELETE', max_length=10, verbose_name='HTTP Method')),
                ('path', models.CharField(blank=True, default='', help_text="API path that was called, e.g. '/api/v1/admin/products/5'", max_length=255, verbose_name='API Path')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the admin', null=True, verbose_name='IP Address')),
                ('status_code', models.PositiveIntegerField(blank=True, help_text='HTTP response status code', null=True, verbose_name='Status Code')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action: request body fields, changed fields, before/after state, reason strings, etc.', verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('admin_user', models.ForeignKey(blank=True, help_text='The admin who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Admin User')),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'db_table': 'billing_admin_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
