# Generated by Django 5.2.13 on 2026-05-30 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_servicedomain_webhook_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPool',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField(help_text='Total amount the user paid for this credit pool, in cents', verbose_name='Amount Paid (cents)')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('credit_periods', models.PositiveIntegerField(help_text='Number of billing periods this credit pool covers', verbose_name='Billing Periods Covered')),
                ('periods_consumed', models.PositiveIntegerField(default=0, verbose_name='Periods Consumed')),
                ('source', models.CharField(choices=[('manual', 'Manual (Admin)'), ('local_gateway', 'Local Payment Gateway'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash Payment')], default='manual', max_length=20, verbose_name='Payment Source')),
                ('payment_reference', models.CharField(blank=True, default='', help_text='Bank reference, transaction ID, or admin note', max_length=255, verbose_name='Payment Reference')),
                ('status', models.CharField(choices=[('active', 'Active'), ('exhausted', 'Exhausted'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('activated_at', models.DateTimeField(blank=True, help_text='When the first period begins', null=True, verbose_name='Activated At')),
                ('current_period_start', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Hard expiry — credit pool expires even if periods remain', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_pools', to='billing.plan', verbose_name='Plan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_pools', to='billing.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_pools', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Credit Pool',
                'verbose_name_plural': 'Credit Pools',
                'db_table': 'billing_credit_pool',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, help_text='Locally generated, e.g. SB-CRED-00001', max_length=50, unique=True, verbose_name='Invoice Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], default='issued', max_length=20, verbose_name='Status')),
                ('amount_cents', models.PositiveIntegerField(verbose_name='Amount (cents)')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('tax_cents', models.PositiveIntegerField(default=0, verbose_name='Tax (cents)')),
                ('total_cents', models.PositiveIntegerField(help_text='amount + tax', verbose_name='Total (cents)')),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=255, verbose_name='Payment Reference')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes (not shown to user)')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_invoices', to='billing.plan', verbose_name='Plan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_invoices', to='billing.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_invoices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('credit_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.creditpool', verbose_name='Credit Pool')),
            ],
            options={
                'verbose_name': 'Credit Invoice',
                'verbose_name_plural': 'Credit Invoices',
                'db_table': 'billing_credit_invoice',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('purchase', 'Purchase'), ('period_consume', 'Period Consumed'), ('refund', 'Refund'), ('adjust', 'Admin Adjustment'), ('expire', 'Expiry')], db_index=True, max_length=20, verbose_name='Action')),
                ('periods_delta', models.IntegerField(help_text='Positive for purchase, negative for consume/refund', verbose_name='Periods Delta')),
                ('amount_cents_delta', models.IntegerField(help_text='Positive for purchase, negative for refund/adjust', verbose_name='Amount Delta (cents)')),
                ('periods_balance', models.PositiveIntegerField(help_text='Periods remaining after this transaction', verbose_name='Running Period Balance')),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('credit_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.creditpool', verbose_name='Credit Pool')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.creditinvoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'db_table': 'billing_credit_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
