# Generated by Django 5.2.13 on 2026-05-31 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_credit_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPurchaseRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField(help_text='How many credits the user wants to buy, in cents', verbose_name='Amount (cents)')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('account_holder_name', models.CharField(max_length=200, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('routing_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Routing Number')),
                ('transaction_reference', models.CharField(help_text='Bank transaction ID or UPI reference', max_length=255, verbose_name='Transaction Reference')),
                ('payment_proof_note', models.TextField(blank=True, default='', help_text='Optional note from the user about the payment', verbose_name='Payment Proof Note')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('review_note', models.TextField(blank=True, default='', help_text='Admin notes (reason for approval/rejection)', verbose_name='Review Note')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_credit_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='billing.creditpool', verbose_name='Created Credit Pool')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_requests', to='billing.plan', verbose_name='Plan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to='billing.product', verbose_name='Product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Credit Purchase Request',
                'verbose_name_plural': 'Credit Purchase Requests',
                'db_table': 'billing_credit_purchase_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
