# Generated by Django 5.2.13 on 2026-05-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_credit_purchase_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('account_holder_name', models.CharField(max_length=200, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('routing_number', models.CharField(blank=True, max_length=50, verbose_name='Routing/SWIFT Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Bank Setting',
                'verbose_name_plural': 'Bank Settings',
                'db_table': 'billing_bank_settings',
            },
        ),
    ]
