# Generated by Django 5.2.13 on 2026-06-01 02:54

import billing.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_bank_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banksettings',
            name='account_number',
            field=billing.fields.EncryptedCharField(max_length=50, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='banksettings',
            name='routing_number',
            field=billing.fields.EncryptedCharField(blank=True, max_length=50, verbose_name='Routing/SWIFT Number'),
        ),
        migrations.AlterField(
            model_name='creditpurchaserequest',
            name='account_number',
            field=billing.fields.EncryptedCharField(max_length=50, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='creditpurchaserequest',
            name='routing_number',
            field=billing.fields.EncryptedCharField(blank=True, default='', max_length=50, verbose_name='Routing Number'),
        ),
    ]
