# Generated by Django 5.2.13 on 2026-06-01 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_alter_banksettings_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='The subscription this invoice belongs to (nullable for history preservation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.subscription', verbose_name='Subscription'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='The subscription this refund is for (nullable for audit trail preservation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='billing.subscription', verbose_name='Subscription'),
        ),
        migrations.AddConstraint(
            model_name='creditpurchaserequest',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_reference__gt', '')), fields=('user', 'transaction_reference'), name='unique_user_transaction_reference', violation_error_message='You have already submitted a request with this transaction reference.'),
        ),
        migrations.AddConstraint(
            model_name='servicedomain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_domain_per_product', violation_error_message='Each product can have only one primary domain.'),
        ),
    ]
