# Generated by Django 5.2.13 on 2026-06-01 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_alter_invoice_subscription_alter_refund_subscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinvoice',
            name='credit_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.creditpool', verbose_name='Credit Pool'),
        ),
        migrations.AddIndex(
            model_name='creditpool',
            index=models.Index(fields=['user', 'status'], name='credit_pool_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpool',
            index=models.Index(fields=['user', 'product'], name='credit_pool_user_product_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpool',
            index=models.Index(fields=['status', 'current_period_end'], name='credit_pool_status_period_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpool',
            index=models.Index(fields=['status', 'expires_at'], name='credit_pool_status_expires_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditpool',
            constraint=models.CheckConstraint(condition=models.Q(('periods_consumed__lte', models.F('credit_periods'))), name='periods_consumed_lte_credit_periods'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_product_id__isnull', False), models.Q(('stripe_product_id', ''), _negated=True)), fields=('stripe_product_id',), name='unique_stripe_product_id'),
        ),
    ]
