# Generated by Django 5.2.13 on 2026-06-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_alter_creditinvoice_credit_pool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpurchaserequest',
            name='credit_periods',
            field=models.PositiveIntegerField(default=1, help_text='Number of billing periods (months/years) the user is committing to.', verbose_name='Credit Periods'),
        ),
    ]
