# Generated by Django 5.2.13 on 2026-06-04 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_creditpurchaserequest_credit_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNotificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('expiry_14d', '14-Day Expiry Warning'), ('expiry_7d', '7-Day Expiry Warning'), ('expiry_1d', '1-Day Expiry Warning (Final Notice)')], db_index=True, help_text='The type of expiry warning that was sent', max_length=30, verbose_name='Notification Type')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the notification email was sent', verbose_name='Sent At')),
                ('credit_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='billing.creditpool', verbose_name='Credit Pool')),
            ],
            options={
                'verbose_name': 'Credit Notification Log',
                'verbose_name_plural': 'Credit Notification Logs',
                'db_table': 'billing_credit_notification_log',
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('credit_pool', 'notification_type'), name='unique_notification_per_pool', violation_error_message='This notification type has already been sent for this credit pool.')],
            },
        ),
    ]
