"""
Django settings for base project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
import sys
from datetime import timedelta

env = environ.Env(SB_DEBUG=(bool, False))

BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR.parent, ".env"))

SECRET_KEY = env("SB_SECRET_KEY")
DEBUG = env.bool("SB_DEBUG", default=False)

ALLOWED_HOSTS = env.list("SB_ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "daphne",  # Must be at the top
    "admin_interface",
    "colorfield",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "django_celery_results",
    "django_celery_beat",
    "ninja_extra",
    "ninja_jwt",
    "ninja_jwt.token_blacklist",
    "corsheaders",
    "users",
    "api",
    "common",
    "billing",
    "cache_cleaner",
]
SILENCED_SYSTEM_CHECKS = ["security.W019"]

# --- Frontend URL ---
# The frontend runs on a separate domain/port (Docker).  This setting ensures
# the backend accepts requests from the frontend origin for CORS, CSRF,
# and Stripe redirect URLs.  Automatically added to CORS_ALLOWED_ORIGINS
# and CSRF_TRUSTED_ORIGINS so you don't need to duplicate it in both lists.
FRONTEND_URL = env("PUBLIC_SITE_URL_SB", default="http://localhost:4321").rstrip("/")

if DEBUG:
    FRONTEND_URL = "http://localhost:4321"

CORS_ALLOW_ALL_ORIGINS = env("SB_CORS_ALLOW_ALL_ORIGINS", default=DEBUG, cast=bool)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = env.list(
    "SB_CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:4321",
        "http://localhost:8090",
        "http://127.0.0.1:4321",
        "http://127.0.0.1:8090",
    ],
)

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-service-domain",
    "x-api-key",
]

CORS_EXPOSE_HEADERS = [
    "x-api-key",
    "x-service-domain",
]

# Ensure the frontend URL is always in CORS_ALLOWED_ORIGINS.
if FRONTEND_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)

CSRF_TRUSTED_ORIGINS = env.list(
    "SB_CSRF_TRUSTED_ORIGINS",
    default=[
        "http://localhost:4321",
        "http://localhost:8090",
        "http://127.0.0.1:4321",
        "http://127.0.0.1:8090",
    ],
)

# Ensure the frontend URL is always in CSRF_TRUSTED_ORIGINS.
if FRONTEND_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)
    



MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "common.cors_middleware.service_domain_cors_middleware",
    "django.middleware.common.CommonMiddleware",
    "ninja.compatibility.files.fix_request_files_middleware",  # <-- ADD THIS LINE
    "common.middleware.service_credential_middleware", 
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "base.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "base.wsgi.application"
ASGI_APPLICATION = "base.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("SB_DB_NAME"),
        "USER": env("SB_DB_USER"),
        "PASSWORD": env("SB_DB_PASSWORD"),
        "HOST": env("SB_DB_HOST"),
        "PORT": env("SB_DB_PORT"),
    }
}

if DEBUG:    
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
    print(
        "WARNING: PostgreSQL settings not fully configured. Falling back to SQLite for development."
    )
    

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

REDIS_HOST = env("SB_REDIS_HOST", default="localhost")
REDIS_PORT = env("SB_REDIS_PORT", default=6379, cast=int)

if DEBUG:
    REDIS_HOST = "localhost"
    REDIS_PORT = 6379
    print(
        f"Using Redis at {REDIS_HOST}:{REDIS_PORT} for Channels, Celery, and Caching. Make sure Redis is running."
    )

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/1'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_RESULT_EXTENDED = True
CELERY_CACHE_BACKEND = "default"
CELERY_RESULT_BACKEND = "django-db"
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_TRACK_STARTED = True
CELERY_TIMEZONE = "UTC"



CACHE_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/2'
CACHE_MIDDLEWARE_SECONDS = 3600

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# if DEBUG:
#     STATICFILES_DIRS = [
#         os.path.join(BASE_DIR, "static"),
#     ]
# else:
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DATA_UPLOAD_MAX_MEMORY_SIZE = 2_621_440  # 2.5 MB — max request body in memory
FILE_UPLOAD_MAX_MEMORY_SIZE = 2_621_440  # 2.5 MB — files below this stored in memory
DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("SB_EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env("SB_EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = env("SB_EMAIL_USE_TLS", default=False, cast=bool)
EMAIL_USE_SSL = env("SB_EMAIL_USE_SSL", default=True, cast=bool)
EMAIL_HOST_USER = env("SB_EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("SB_EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = env("SB_DEFAULT_FROM_EMAIL")

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30
X_FRAME_OPTIONS = "SAMEORIGIN"

SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "lax"
    FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o777
    FILE_UPLOAD_PERMISSIONS = 0o644
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_HOST = None  # Set to hostname string in production, not True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_NAME = env("SB_SESSION_COOKIE_NAME", default="sessionid")

    # HSTS — enforce HTTPS
    SECURE_HSTS_SECONDS = env(
        "SB_SECURE_HSTS_SECONDS", default=31536000, cast=int
    )  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Require separate JWT signing key in production (never fall back to SECRET_KEY)
    _jwt_key = env("SB_JWT_SIGNING_KEY", default=None)
    if _jwt_key is None:
        raise environ.ImproperlyConfigured(
            "SB_JWT_SIGNING_KEY must be set explicitly in production (not defaulting to SECRET_KEY)."
        )

# --- Rate Limiting ---
RATE_LIMIT_LOGIN_ATTEMPTS = env("SB_RATE_LIMIT_LOGIN_ATTEMPTS", default=10, cast=int)
RATE_LIMIT_LOGIN_WINDOW = env(
    "SB_RATE_LIMIT_LOGIN_WINDOW", default=900, cast=int
)  # 15 min
RATE_LIMIT_REGISTER_ATTEMPTS = env("SB_RATE_LIMIT_REGISTER_ATTEMPTS", default=5, cast=int)
RATE_LIMIT_REGISTER_WINDOW = env(
    "SB_RATE_LIMIT_REGISTER_WINDOW", default=3600, cast=int
)  # 1 hour
RATE_LIMIT_PASSWORD_RESET_ATTEMPTS = env(
    "SB_RATE_LIMIT_PASSWORD_RESET_ATTEMPTS", default=5, cast=int
)
RATE_LIMIT_PASSWORD_RESET_WINDOW = env(
    "SB_RATE_LIMIT_PASSWORD_RESET_WINDOW", default=3600, cast=int
)  # 1 hour

# --- Password Reset ---
PASSWORD_RESET_TOKEN_EXPIRY_SECONDS = env(
    "SB_PASSWORD_RESET_TOKEN_EXPIRY", default=900, cast=int
)  # 15 min

RATE_LIMIT_SENSITIVE_ATTEMPTS = env(
    "SB_RATE_LIMIT_SENSITIVE_ATTEMPTS", default=5, cast=int
)
RATE_LIMIT_SENSITIVE_WINDOW = env(
    "SB_RATE_LIMIT_SENSITIVE_WINDOW", default=3600, cast=int
)  # 1 hour
# --- Email Change --- 
EMAIL_CHANGE_TOKEN_EXPIRY_SECONDS = env(
    "SB_EMAIL_CHANGE_TOKEN_EXPIRY", default=3600, cast=int
)  # 1 hour
 
# --- API Key Authentication ---
# When True, requests with an invalid or revoked X-API-Key receive an
# immediate 403 response.  When False (default), invalid keys log a warning
# but the request passes through — useful for gradual rollout during
# development.  **Must be set to True before deploying SDK consumers to
# production.**  Controlled via SB_API_KEY_ENFORCED env var.
API_KEY_ENFORCED = env("SB_API_KEY_ENFORCED", default=False, cast=bool)

# Production safety check: warn if enforcement is off in production mode.
if not API_KEY_ENFORCED and not DEBUG:
    import warnings
    warnings.warn(
        "API_KEY_ENFORCED is False in non-debug mode. "
        "Set SB_API_KEY_ENFORCED=True before deploying to production. "
        "Invalid API keys will be logged but allowed through.",
        RuntimeWarning,
        stacklevel=1,
    )

# --- SDK Rate Limiting (server-to-server traffic via X-API-Key) ---
# Higher limits than per-IP because SDK traffic comes from trusted
# sister domain backends that proxy many users through one IP.
RATE_LIMIT_SDK_ATTEMPTS = env("SB_RATE_LIMIT_SDK_ATTEMPTS", default=1000, cast=int)
RATE_LIMIT_SDK_WINDOW = env("SB_RATE_LIMIT_SDK_WINDOW", default=3600, cast=int)  # 1 hour




FORMATTERS = (
    {
        "verbose": {
            "format": "{levelname} {asctime} {name} {threadName} {thread} {pathname} {lineno} {funcName} {process} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {pathname} {lineno} {message}",
            "style": "{",
        },
    },
)

HANDLERS = {
    "console_handler": {
        "class": "logging.StreamHandler",
        "formatter": "simple",
        "level": "DEBUG",
    },
    "info_handler": {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": os.path.join(BASE_DIR, "logs/info.log"),
        "mode": "a",
        "encoding": "utf-8",
        "formatter": "verbose",
        "level": "INFO",
        "backupCount": 5,
        "maxBytes": 1024 * 1024 * 5,  # 5 MB
    },
    "error_handler": {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": os.path.join(BASE_DIR, "logs/error.log"),
        "mode": "a",
        "formatter": "verbose",
        "level": "WARNING",
        "backupCount": 5,
        "maxBytes": 1024 * 1024 * 5,  # 5 MB
    },
    "debug_handler": {
        "filename": os.path.join(BASE_DIR, "logs/debug.log"),
        "mode": "a",
        "maxBytes": 1024 * 1024 * 5,  # 5 MB
        "class": "logging.handlers.RotatingFileHandler",
        "formatter": "simple",
        "encoding": "utf-8",
        "level": "DEBUG",
        "backupCount": 5,
    },
}

LOGGERS = (
    {
        "django": {
            "handlers": ["console_handler", "info_handler"],
            "level": "INFO",
        },
        "django.request": {
            "handlers": ["error_handler"],
            "level": "INFO",
            "propagate": True,
        },
        "django.template": {
            "handlers": ["error_handler"],
            "level": "INFO",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["error_handler"],
            "level": "INFO",
            "propagate": True,
        },
        "log": {
            "handlers": ["console_handler", "debug_handler"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": FORMATTERS[0],
    "handlers": HANDLERS,
    "loggers": LOGGERS[0],
}


AUTH_USER_MODEL = "users.User"

# --- JWT Configuration ---
NINJA_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=env("SB_JWT_ACCESS_TOKEN_MINUTES", default=60)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=env("SB_JWT_REFRESH_TOKEN_DAYS", default=7)),
    "ROTATE_REFRESH_TOKENS": env("SB_JWT_ROTATE_REFRESH_TOKENS", default=True, cast=bool),
    "BLACKLIST_AFTER_ROTATION": env(
        "SB_JWT_BLACKLIST_AFTER_ROTATION", default=True, cast=bool
    ),
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": env("SB_JWT_ALGORITHM", default="HS256"),
    "SIGNING_KEY": env("SB_JWT_SIGNING_KEY", default=SECRET_KEY),
    "USE_STATELESS_AUTH": True,
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}


# --- User Roles ---
USER_ROLES = ["owner", "admin", "member"]


# --- Stripe Configuration ---
STRIPE_SECRET_KEY = env("SB_STRIPE_SECRET_KEY", default="")
STRIPE_PUBLISHABLE_KEY = env("SB_STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_WEBHOOK_SECRET = env("SB_STRIPE_WEBHOOK_SECRET", default="")
STRIPE_APP_DOMAIN = env("SB_STRIPE_APP_DOMAIN", default=FRONTEND_URL)
if DEBUG:
    STRIPE_APP_DOMAIN = FRONTEND_URL
    
STRIPE_PORTAL_RETURN_URL = env(
    "SB_STRIPE_PORTAL_RETURN_URL",
    default=f"{STRIPE_APP_DOMAIN}/dashboard/billing",
)
STRIPE_SUCCESS_URL = env(
    "SB_STRIPE_SUCCESS_URL",
    default=f"{STRIPE_APP_DOMAIN}/dashboard/billing?checkout=success",
)
STRIPE_CANCEL_URL = env(
    "SB_STRIPE_CANCEL_URL",
    default=f"{STRIPE_APP_DOMAIN}/dashboard/billing?checkout=canceled",
)

# --- F6: Tax Control ---
# Must be explicitly set to True when Stripe Tax is activated in Dashboard.
# If False, automatic_tax will be disabled at checkout to prevent
# silently charging without tax (regulatory non-compliance).
STRIPE_TAX_ENABLED = env("SB_STRIPE_TAX_ENABLED", default=False, cast=bool)

# --- Base Currency for Billing ---
# All plan prices are stored in this currency. When displaying prices to
# users, the frontend sends the user's preferred currency and the backend
# converts using the exchange rates stored in ExchangeRate model.
BASE_CURRENCY = env("SB_BASE_CURRENCY", default="USD")

# --- Exchange Rate API ---
# Free API for fetching daily exchange rates. No API key required.
# Used by the update_exchange_rates Celery task.
EXCHANGE_RATE_API_URL = env(
    "SB_EXCHANGE_RATE_API_URL",
    default="https://open.er-api.com/v6/latest",
)

# --- F7: Terms of Service Version ---
# Increment this when updating Terms of Service. Used to track which
# version the user accepted. Displayed in the ToS acceptance audit trail.
TOS_VERSION = env("SB_TOS_VERSION", default="1.0")
