# Generated by Django 5.2.13 on 2026-06-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DSR',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('DSR', 'DSR'), ('Order Collector', 'Order Collector')], default='DSR', max_length=20)),
                ('parent_dsr_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_dsr', models.ForeignKey(blank=True, db_column='parent_dsr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='dsr.dsr')),
            ],
            options={
                'verbose_name': 'DSR',
                'verbose_name_plural': 'DSRs',
                'ordering': ['name'],
            },
        ),
    ]
