# Generated by Django 5.2.13 on 2026-06-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dsr',
            index=models.Index(fields=['parent_dsr', 'role'], name='dsr_dsr_parent__86994c_idx'),
        ),
        migrations.AddIndex(
            model_name='dsr',
            index=models.Index(fields=['role'], name='dsr_dsr_role_0a819c_idx'),
        ),
    ]
