# Generated by Django 5.2.13 on 2026-06-10 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_dealerconfig_address_dealerconfig_business_name_and_more'),
        ('dsr', '0002_dsr_dsr_dsr_parent__86994c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DsrDealerAssignment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('DSR', 'DSR'), ('Collector', 'Order Collector')], default='DSR', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage for this DSR with this dealer', max_digits=5, null=True)),
                ('dealer', models.ForeignKey(db_column='dealer_username', on_delete=django.db.models.deletion.CASCADE, related_name='dsr_assignments', to='dealer.dealerconfig')),
                ('dsr', models.ForeignKey(db_column='dsr_id', on_delete=django.db.models.deletion.CASCADE, related_name='dealer_assignments', to='dsr.dsr')),
                ('parent_dsr', models.ForeignKey(blank=True, db_column='parent_dsr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_assignments', to='dsr.dsr')),
            ],
            options={
                'verbose_name': 'DSR Dealer Assignment',
                'verbose_name_plural': 'DSR Dealer Assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['dealer', 'is_active', 'role'], name='dsr_dsrdeal_dealer__817984_idx'), models.Index(fields=['dsr', 'is_active'], name='dsr_dsrdeal_dsr_id_9aba5f_idx'), models.Index(fields=['parent_dsr', 'is_active'], name='dsr_dsrdeal_parent__5411d5_idx')],
                'constraints': [models.UniqueConstraint(fields=('dsr', 'dealer'), name='unique_dsr_dealer_assignment')],
            },
        ),
        migrations.CreateModel(
            name='DsrInvitation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('DSR', 'DSR'), ('Collector', 'Order Collector')], default='DSR', max_length=20)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('accepted_by', models.ForeignKey(blank=True, db_column='accepted_by_dsr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to='dsr.dsr')),
                ('dealer', models.ForeignKey(db_column='dealer_username', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='dealer.dealerconfig')),
                ('parent_dsr', models.ForeignKey(blank=True, db_column='parent_dsr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collector_invitations', to='dsr.dsr')),
            ],
            options={
                'verbose_name': 'DSR Invitation',
                'verbose_name_plural': 'DSR Invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dealer', 'status'], name='dsr_dsrinvi_dealer__cf95f3_idx'), models.Index(fields=['email', 'status'], name='dsr_dsrinvi_email_c64163_idx'), models.Index(fields=['token'], name='dsr_dsrinvi_token_871cce_idx'), models.Index(fields=['expires_at'], name='dsr_dsrinvi_expires_fa25b4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('dealer', 'email'), name='unique_pending_invitation_per_dealer_email')],
            },
        ),
    ]
