# Generated by Django 5.2.13 on 2026-06-12 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_dealerconfig_address_dealerconfig_business_name_and_more'),
        ('dsr', '0003_dsrdealerassignment_dsrinvitation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dsrinvitation',
            name='unique_pending_invitation_per_dealer_email',
        ),
        migrations.RemoveIndex(
            model_name='dsrdealerassignment',
            name='dsr_dsrdeal_dealer__817984_idx',
        ),
        migrations.RemoveIndex(
            model_name='dsrdealerassignment',
            name='dsr_dsrdeal_dsr_id_9aba5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='dsrdealerassignment',
            name='dsr_dsrdeal_parent__5411d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='dsrinvitation',
            name='dsr_dsrinvi_email_c64163_idx',
        ),
        migrations.RemoveField(
            model_name='dsrdealerassignment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dsrinvitation',
            name='email',
        ),
        migrations.AddField(
            model_name='dsrdealerassignment',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsrdealerassignment',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Per-dealer permissions for this DSR'),
        ),
        migrations.AddField(
            model_name='dsrdealerassignment',
            name='removal_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for removal/leaving'),
        ),
        migrations.AddField(
            model_name='dsrdealerassignment',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsrdealerassignment',
            name='removed_by',
            field=models.CharField(blank=True, default='', help_text="Who initiated removal: 'dealer' or 'dsr'", max_length=20),
        ),
        migrations.AddField(
            model_name='dsrdealerassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('removed', 'Removed by Dealer'), ('left', 'Left by DSR')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='dsrinvitation',
            name='dsr',
            field=models.ForeignKey(blank=True, db_column='dsr_id', help_text='Link to DSR if already registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to='dsr.dsr'),
        ),
        migrations.AddField(
            model_name='dsrinvitation',
            name='dsr_email',
            field=models.EmailField(blank=True, default='', help_text='DSR email (optional, for notifications)', max_length=254),
        ),
        migrations.AddField(
            model_name='dsrinvitation',
            name='dsr_phone',
            field=models.CharField(db_index=True, default='', help_text='DSR phone number (primary identifier)', max_length=20),
        ),
        migrations.AddField(
            model_name='dsrinvitation',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Permissions being offered to this DSR'),
        ),
        migrations.AddField(
            model_name='dsrinvitation',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When DSR accepted/rejected', null=True),
        ),
        migrations.AlterField(
            model_name='dsrdealerassignment',
            name='role',
            field=models.CharField(choices=[('DSR', 'DSR'), ('Senior_DSR', 'Senior DSR'), ('Manager', 'Manager'), ('Collector', 'Order Collector')], default='DSR', max_length=20),
        ),
        migrations.AlterField(
            model_name='dsrinvitation',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Personal message from dealer to DSR'),
        ),
        migrations.AlterField(
            model_name='dsrinvitation',
            name='role',
            field=models.CharField(choices=[('DSR', 'DSR'), ('Senior_DSR', 'Senior DSR'), ('Manager', 'Manager'), ('Collector', 'Order Collector')], default='DSR', max_length=20),
        ),
        migrations.AlterField(
            model_name='dsrinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dsrdealerassignment',
            index=models.Index(fields=['dealer', 'status', 'role'], name='dsr_dsrdeal_dealer__d09100_idx'),
        ),
        migrations.AddIndex(
            model_name='dsrdealerassignment',
            index=models.Index(fields=['dsr', 'status'], name='dsr_dsrdeal_dsr_id_89f251_idx'),
        ),
        migrations.AddIndex(
            model_name='dsrdealerassignment',
            index=models.Index(fields=['parent_dsr', 'status'], name='dsr_dsrdeal_parent__b41183_idx'),
        ),
        migrations.AddIndex(
            model_name='dsrinvitation',
            index=models.Index(fields=['dsr_phone', 'status'], name='dsr_dsrinvi_dsr_pho_b907de_idx'),
        ),
        migrations.AddIndex(
            model_name='dsrinvitation',
            index=models.Index(fields=['dsr_email', 'status'], name='dsr_dsrinvi_dsr_ema_b9aed5_idx'),
        ),
        migrations.AddIndex(
            model_name='dsrinvitation',
            index=models.Index(fields=['dsr', 'status'], name='dsr_dsrinvi_dsr_id_9a79f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='dsrinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('dealer', 'dsr_phone'), name='unique_pending_invitation_per_dealer_phone'),
        ),
    ]
