# Generated by Django 5.2.13 on 2026-06-13 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0004_remove_dsrinvitation_unique_pending_invitation_per_dealer_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dsr',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='dsr',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account for login (null for legacy DSRs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dsr',
            index=models.Index(fields=['user'], name='dsr_dsr_user_id_6b72fa_idx'),
        ),
        migrations.AddIndex(
            model_name='dsr',
            index=models.Index(fields=['email'], name='dsr_dsr_email_ba685b_idx'),
        ),
    ]
