# Generated by Django 5.2.13 on 2026-06-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_dealerconfig_address_dealerconfig_business_name_and_more'),
        ('dsr', '0005_dsr_email_dsr_user_dsr_dsr_dsr_user_id_6b72fa_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dsrinvitation',
            name='unique_pending_invitation_per_dealer_phone',
        ),
        migrations.AddConstraint(
            model_name='dsrinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), models.Q(('dsr_phone', ''), _negated=True)), fields=('dealer', 'dsr_phone'), name='unique_pending_invitation_per_dealer_phone'),
        ),
    ]
