# Generated by Django 5.2.13 on 2026-06-13 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_dealerconfig_address_dealerconfig_business_name_and_more'),
        ('dsr', '0006_remove_dsrinvitation_unique_pending_invitation_per_dealer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsrdealerassignment',
            name='dealer',
            field=models.ForeignKey(blank=True, db_column='dealer_username', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_assignments', to='dealer.dealerconfig'),
        ),
        migrations.AlterField(
            model_name='dsrdealerassignment',
            name='dsr',
            field=models.ForeignKey(blank=True, db_column='dsr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_assignments', to='dsr.dsr'),
        ),
    ]
