# Generated by Django 5.2.13 on 2026-06-14 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0007_alter_dsrdealerassignment_dealer_and_more'),
        ('sales', '0009_alter_salerecord_dsr_alter_salerecord_original_dsr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsrdealerassignment',
            name='dsr',
            field=models.ForeignKey(blank=True, db_column='dsr_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dsrinvitation',
            name='parent_dsr',
            field=models.ForeignKey(blank=True, db_column='parent_dsr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collector_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dsrinvitation',
            name='dsr',
            field=models.ForeignKey(blank=True, db_column='dsr_id', help_text='Link to DSR if already registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dsrdealerassignment',
            name='parent_dsr',
            field=models.ForeignKey(blank=True, db_column='parent_dsr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dsrinvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, db_column='accepted_by_dsr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DSR',
        ),
    ]
