# Generated by Django 5.2.13 on 2026-04-27 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_passwordresettoken_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('HKD', 'Hong Kong Dollar'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('KRW', 'South Korean Won'), ('SGD', 'Singapore Dollar'), ('INR', 'Indian Rupee'), ('MXN', 'Mexican Peso'), ('BRL', 'Brazilian Real'), ('ZAR', 'South African Rand'), ('RUB', 'Russian Ruble'), ('TRY', 'Turkish Lira'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('BDT', 'Bangladeshi Taka'), ('PKR', 'Pakistani Rupee'), ('PHP', 'Philippine Peso'), ('THB', 'Thai Baht'), ('MYR', 'Malaysian Ringgit'), ('IDR', 'Indonesian Rupiah'), ('VND', 'Vietnamese Dong'), ('NOK', 'Norwegian Krone'), ('DKK', 'Danish Krone'), ('PLN', 'Polish Zloty'), ('TWD', 'Taiwan Dollar'), ('NGN', 'Nigerian Naira'), ('EGP', 'Egyptian Pound'), ('KES', 'Kenyan Shilling'), ('COP', 'Colombian Peso'), ('CLP', 'Chilean Peso'), ('PEN', 'Peruvian Sol'), ('ARS', 'Argentine Peso')], db_index=True, default='USD', max_length=3, verbose_name='Preferred Currency'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('pt', 'Portuguese'), ('it', 'Italian'), ('nl', 'Dutch'), ('ru', 'Russian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('tr', 'Turkish'), ('pl', 'Polish'), ('sv', 'Swedish'), ('da', 'Danish'), ('no', 'Norwegian'), ('fi', 'Finnish'), ('th', 'Thai'), ('vi', 'Vietnamese'), ('id', 'Indonesian'), ('ms', 'Malay'), ('tl', 'Filipino'), ('uk', 'Ukrainian'), ('cs', 'Czech'), ('hu', 'Hungarian'), ('ro', 'Romanian'), ('el', 'Greek')], db_index=True, default='en', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], db_index=True, default='member', help_text='User role: owner, admin, member', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('America/New_York', 'Eastern Time (US)'), ('America/Chicago', 'Central Time (US)'), ('America/Denver', 'Mountain Time (US)'), ('America/Los_Angeles', 'Pacific Time (US)'), ('America/Anchorage', 'Alaska Time (US)'), ('Pacific/Honolulu', 'Hawaii Time (US)'), ('America/Toronto', 'Eastern Time (Canada)'), ('America/Vancouver', 'Pacific Time (Canada)'), ('America/Mexico_City', 'Mexico City'), ('America/Sao_Paulo', 'Sao Paulo'), ('America/Argentina/Buenos_Aires', 'Buenos Aires'), ('America/Bogota', 'Bogota'), ('America/Lima', 'Lima'), ('America/Santiago', 'Santiago'), ('Europe/London', 'London'), ('Europe/Dublin', 'Dublin'), ('Europe/Paris', 'Paris'), ('Europe/Berlin', 'Berlin'), ('Europe/Madrid', 'Madrid'), ('Europe/Rome', 'Rome'), ('Europe/Amsterdam', 'Amsterdam'), ('Europe/Brussels', 'Brussels'), ('Europe/Vienna', 'Vienna'), ('Europe/Stockholm', 'Stockholm'), ('Europe/Oslo', 'Oslo'), ('Europe/Copenhagen', 'Copenhagen'), ('Europe/Helsinki', 'Helsinki'), ('Europe/Warsaw', 'Warsaw'), ('Europe/Lisbon', 'Lisbon'), ('Europe/Athens', 'Athens'), ('Europe/Prague', 'Prague'), ('Europe/Budapest', 'Budapest'), ('Europe/Bucharest', 'Bucharest'), ('Asia/Dubai', 'Dubai'), ('Asia/Riyadh', 'Riyadh'), ('Asia/Kolkata', 'India Standard Time'), ('Asia/Karachi', 'Karachi'), ('Asia/Dhaka', 'Dhaka'), ('Asia/Colombo', 'Colombo'), ('Asia/Kathmandu', 'Kathmandu'), ('Asia/Bangkok', 'Bangkok'), ('Asia/Ho_Chi_Minh', 'Ho Chi Minh City'), ('Asia/Jakarta', 'Jakarta'), ('Asia/Kuala_Lumpur', 'Kuala Lumpur'), ('Asia/Singapore', 'Singapore'), ('Asia/Manila', 'Manila'), ('Asia/Shanghai', 'Shanghai'), ('Asia/Hong_Kong', 'Hong Kong'), ('Asia/Taipei', 'Taipei'), ('Asia/Seoul', 'Seoul'), ('Asia/Tokyo', 'Tokyo'), ('Australia/Sydney', 'Sydney'), ('Australia/Melbourne', 'Melbourne'), ('Australia/Perth', 'Perth'), ('Pacific/Auckland', 'Auckland'), ('Africa/Johannesburg', 'Johannesburg'), ('Africa/Nairobi', 'Nairobi'), ('Africa/Cairo', 'Cairo'), ('Africa/Lagos', 'Lagos'), ('Africa/Casablanca', 'Casablanca')], db_index=True, default='UTC', max_length=50, verbose_name='Timezone'),
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address from which the login originated.', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser/client user agent string.', verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Login Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login History',
                'db_table': 'users_login_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
