# Generated by Django 5.2.13 on 2026-04-27 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='domain',
        ),
        migrations.CreateModel(
            name='ServiceDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, help_text="Service domain, e.g. 'finance.sattabase.tld'. This is matched against the X-Service-Domain header.", max_length=255, unique=True, verbose_name='Domain')),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='The primary domain for the product. Used in product detail responses and admin displays.', verbose_name='Primary Domain')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this domain is accepting requests', verbose_name='Active')),
                ('product', models.ForeignKey(help_text='The product this domain serves subscriptions for', on_delete=django.db.models.deletion.CASCADE, related_name='service_domains', to='billing.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Service Domain',
                'verbose_name_plural': 'Service Domains',
                'db_table': 'billing_service_domain',
                'ordering': ['-is_primary', 'domain'],
            },
        ),
    ]
