# Generated by Django 5.2.13 on 2026-04-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_product_domain_servicedomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, help_text='Stripe event ID, e.g. evt_1Pxxx...', max_length=255, unique=True, verbose_name='Stripe Event ID')),
                ('event_type', models.CharField(db_index=True, help_text='Stripe event type, e.g. checkout.session.completed', max_length=100, verbose_name='Event Type')),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Whether this event has been successfully processed', verbose_name='Processed')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if processing failed', verbose_name='Error Message')),
                ('payload', models.JSONField(default=dict, help_text='Full Stripe event JSON payload', verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Webhook Event Log',
                'verbose_name_plural': 'Webhook Event Logs',
                'db_table': 'billing_webhook_event_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
