# Generated by Django 5.2.13 on 2026-04-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_webhookeventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Auto-created when the first paid plan checkout is initiated', max_length=100, null=True, verbose_name='Stripe Product ID'),
        ),
    ]
