# Generated by Django 5.2.13 on 2026-04-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_subscription_currency_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='dunning_step',
            field=models.PositiveIntegerField(default=0, help_text='Current dunning workflow step (0=none, 1=reminder, 2=urgent, 3=restrict, 4=cancel). Incremented by the dunning_retry Celery task.', verbose_name='Dunning Step'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_dunning_email_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last dunning email sent for this subscription. Used to prevent duplicate emails.', null=True, verbose_name='Last Dunning Email At'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('stripe_invoice_id', models.CharField(db_index=True, help_text='Stripe Invoice ID, e.g. in_1Pxxx...', max_length=100, unique=True, verbose_name='Stripe Invoice ID')),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, default='', help_text='Denormalized for quick filtering without JOIN', max_length=100, verbose_name='Stripe Subscription ID')),
                ('number', models.CharField(blank=True, default='', help_text='Stripe invoice number, e.g. INV-0012', max_length=50, verbose_name='Invoice Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('uncollectible', 'Uncollectible'), ('void', 'Void')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('amount_paid_cents', models.PositiveIntegerField(default=0, help_text='Amount paid by the customer in cents', verbose_name='Amount Paid (cents)')),
                ('amount_due_cents', models.PositiveIntegerField(default=0, help_text='Amount still owed in cents', verbose_name='Amount Due (cents)')),
                ('tax_cents', models.PositiveIntegerField(default=0, help_text='Total tax amount in cents', verbose_name='Tax (cents)')),
                ('discount_cents', models.PositiveIntegerField(default=0, help_text='Total discount amount in cents', verbose_name='Discount (cents)')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3, verbose_name='Currency')),
                ('period_start', models.DateTimeField(blank=True, help_text='Start of the billing period this invoice covers', null=True, verbose_name='Period Start')),
                ('period_end', models.DateTimeField(blank=True, help_text='End of the billing period this invoice covers', null=True, verbose_name='Period End')),
                ('description', models.CharField(blank=True, default='', help_text='Invoice description line (e.g. plan name)', max_length=255, verbose_name='Description')),
                ('hosted_url', models.URLField(blank=True, default='', help_text='Stripe-hosted invoice page URL', verbose_name='Hosted Invoice URL')),
                ('pdf_url', models.URLField(blank=True, default='', help_text='Stripe-hosted invoice PDF URL', verbose_name='PDF URL')),
                ('attempt_count', models.PositiveIntegerField(default=1, help_text='Number of payment attempts for this invoice', verbose_name='Attempt Count')),
                ('next_payment_attempt', models.DateTimeField(blank=True, help_text='When Stripe will next attempt payment', null=True, verbose_name='Next Payment Attempt')),
                ('stripe_response', models.JSONField(blank=True, default=dict, help_text='Full Stripe Invoice object for audit/reconciliation', verbose_name='Stripe Response')),
                ('subscription', models.ForeignKey(help_text='The subscription this invoice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'billing_invoice',
                'ordering': ['-created_at'],
            },
        ),
    ]
