# Generated by Django 5.2.13 on 2026-05-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_subscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_line_item_id', models.CharField(blank=True, db_index=True, default='', help_text='Stripe LineItem ID (e.g. li_1Pxxx...)', max_length=100, verbose_name='Stripe Line Item ID')),
                ('description', models.CharField(blank=True, default='', help_text='Line item description (e.g. plan name, proration)', max_length=255, verbose_name='Description')),
                ('amount_cents', models.IntegerField(default=0, help_text='Line item amount in cents (can be negative for credits)', verbose_name='Amount (cents)')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3, verbose_name='Currency')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units (usually 1 for subscriptions)', verbose_name='Quantity')),
                ('period_start', models.DateTimeField(blank=True, help_text='Start of the service period for this line item', null=True, verbose_name='Period Start')),
                ('period_end', models.DateTimeField(blank=True, help_text='End of the service period for this line item', null=True, verbose_name='Period End')),
                ('proration', models.BooleanField(default=False, help_text='Whether this line item is a proration adjustment', verbose_name='Proration')),
                ('discount_amount_cents', models.IntegerField(default=0, help_text='Discount applied to this line item in cents', verbose_name='Discount Amount (cents)')),
                ('tax_amount_cents', models.IntegerField(default=0, help_text='Tax applied to this line item in cents', verbose_name='Tax Amount (cents)')),
                ('type', models.CharField(blank=True, default='', help_text='Line item type: subscription, invoiceitem, etc.', max_length=30, verbose_name='Type')),
                ('invoice', models.ForeignKey(help_text='The parent invoice this line item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'db_table': 'billing_invoice_line_item',
                'ordering': ['id'],
            },
        ),
    ]
