# Generated by Django 5.2.13 on 2026-05-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedomain',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', help_text='HMAC-SHA256 secret for signing webhook payloads. Shared with the sister domain to verify webhook authenticity.', max_length=255, verbose_name='Webhook Secret'),
        ),
        migrations.AddField(
            model_name='servicedomain',
            name='webhook_url',
            field=models.URLField(blank=True, default='', help_text='URL to receive credential status change notifications (revocation, rotation). Must be HTTPS in production.', verbose_name='Webhook URL'),
        ),
    ]
