# Generated by Django 5.2.13 on 2026-05-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_invoice_card_category_bill_documentvault_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestNote',
        ),
        migrations.AddField(
            model_name='budget',
            name='include_pending',
            field=models.BooleanField(default=False, help_text='If True, PENDING transactions are included in spent_amount. Default is False (only CLEARED transactions count toward budget).'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Auto-calculated as quantity * unit_price if not provided.', max_digits=15),
        ),
    ]
