# Generated by Django 5.2.13 on 2026-06-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dsr', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_vehicle', models.BooleanField(default=False)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=50)),
                ('dsr_name', models.CharField(blank=True, default='', max_length=255)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('collection_status', models.CharField(choices=[('Fully Paid', 'Fully Paid'), ('Pending', 'Pending'), ('Partial', 'Partial')], default='Fully Paid', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('is_closed_with_due', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dsr', models.ForeignKey(blank=True, db_column='dsr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='dsr.dsr')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Sale Record',
                'verbose_name_plural': 'Sale Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateTimeField()),
                ('received_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(db_column='sale_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salerecord')),
            ],
            options={
                'verbose_name': 'Credit Payment',
                'verbose_name_plural': 'Credit Payments',
                'ordering': ['date'],
            },
        ),
    ]
