# Generated by Django 5.2.13 on 2026-06-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='collection_status',
            field=models.CharField(choices=[('Fully Paid', 'Fully Paid'), ('Pending', 'Pending'), ('Partial', 'Partial'), ('Written Off', 'Written Off')], default='Fully Paid', max_length=30),
        ),
    ]
