# Generated by Django 5.2.13 on 2026-06-06 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salerecord_collection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='collection_status',
            field=models.CharField(choices=[('Fully Paid', 'Fully Paid'), ('Pending', 'Pending'), ('Partial', 'Partial'), ('Written Off', 'Written Off'), ('Voided', 'Voided')], default='Fully Paid', max_length=30),
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.CharField(choices=[('Defective', 'Defective'), ('Wrong Item', 'Wrong Item'), ('Customer Return', 'Customer Return'), ('Damaged', 'Damaged'), ('Other', 'Other')], default='Customer Return', max_length=30)),
                ('processed_by', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(db_column='sale_id', on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.salerecord')),
            ],
            options={
                'verbose_name': 'Sale Return',
                'verbose_name_plural': 'Sale Returns',
                'ordering': ['-date'],
            },
        ),
    ]
