# Generated by Django 5.2.13 on 2026-06-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0001_initial'),
        ('sales', '0003_salerecord_is_voided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='original_dsr',
            field=models.ForeignKey(blank=True, db_column='original_dsr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_sales', to='dsr.dsr'),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='original_dsr_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='return_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative total of all return amounts for this sale. Net obligation = total_amount - return_total_amount.', max_digits=14),
        ),
    ]
