# Generated by Django 5.2.13 on 2026-06-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0002_dsr_dsr_dsr_parent__86994c_idx_and_more'),
        ('inventory', '0003_product_inventory_p_stock_ab308e_idx_and_more'),
        ('sales', '0004_salerecord_original_dsr_salerecord_original_dsr_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['customer_name', 'collection_status', 'is_voided', 'is_closed_with_due'], name='sales_saler_custome_d67980_idx'),
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['dsr', 'collection_status', 'is_voided', 'is_closed_with_due'], name='sales_saler_dsr_id_9d85d4_idx'),
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['vehicle_number', 'is_vehicle', 'collection_status'], name='sales_saler_vehicle_635875_idx'),
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['is_voided', 'is_closed_with_due', 'payment_type'], name='sales_saler_is_void_466b71_idx'),
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['date'], name='sales_saler_date_2b4cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['product', 'is_voided', 'is_closed_with_due'], name='sales_saler_product_a44fe2_idx'),
        ),
    ]
