# Generated by Django 5.2.13 on 2026-06-11 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_dealerconfig_address_dealerconfig_business_name_and_more'),
        ('dsr', '0003_dsrdealerassignment_dsrinvitation'),
        ('inventory', '0004_brand_dealer_category_dealer_product_dealer_and_more'),
        ('sales', '0005_salerecord_sales_saler_custome_d67980_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='dealer',
            field=models.ForeignKey(db_column='dealer_username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='dealer.dealerconfig'),
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['dealer', '-date'], name='sales_saler_dealer__0b2eda_idx'),
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['dealer', 'collection_status'], name='sales_saler_dealer__b93699_idx'),
        ),
    ]
