# Generated by Django 5.2.13 on 2026-06-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_salerecord_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='dsr_status',
            field=models.CharField(blank=True, default='active', help_text="Status of DSR at time of sale/removal: 'active', 'removed', 'left'", max_length=20),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='original_dsr_status',
            field=models.CharField(blank=True, default='active', help_text="Status of original DSR: 'active', 'removed', 'left'", max_length=20),
        ),
    ]
