# Generated by Django 5.2.13 on 2026-06-14 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salerecord_dsr_status_salerecord_original_dsr_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='dsr',
            field=models.ForeignKey(blank=True, db_column='dsr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='original_dsr',
            field=models.ForeignKey(blank=True, db_column='original_dsr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
