# Generated by Django 5.2.13 on 2026-06-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerConfig',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(default='Dealer', max_length=100)),
                ('default_currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AED', 'AED'), ('JPY', 'JPY'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('SGD', 'SGD')], default='INR', max_length=3)),
                ('default_locale', models.CharField(default='en-IN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dealer Configuration',
                'verbose_name_plural': 'Dealer Configurations',
                'ordering': ['username'],
            },
        ),
    ]
