# Generated by Django 5.2.13 on 2026-06-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerconfig',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dealerconfig',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dealerconfig',
            name='communication_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dealerconfig',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='dealerconfig',
            name='google_map_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dealerconfig',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dealerconfig',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
