# Generated by Django 5.2.13 on 2026-06-12 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dealer', '0002_dealerconfig_address_dealerconfig_business_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DsrUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Email address used for login', max_length=254, unique=True, verbose_name='email address')),
                ('user_type', models.CharField(choices=[('DSR', 'DSR'), ('Collector', 'Order Collector'), ('ADMIN', 'Admin')], db_index=True, default='DSR', help_text='Type of user: DSR, Collector, or Admin', max_length=20)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='last name')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='phone number')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.CharField(blank=True, default='', max_length=64)),
                ('password_reset_expires', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('selected_dealer', models.ForeignKey(blank=True, help_text='Currently selected dealer context for this DSR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_dsr_sessions', to='dealer.dealerconfig')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'DSR User',
                'verbose_name_plural': 'DSR Users',
                'db_table': 'users_dsr_user',
                'ordering': ['email'],
                'indexes': [models.Index(fields=['email'], name='users_dsr_u_email_71dedb_idx'), models.Index(fields=['user_type', 'is_active'], name='users_dsr_u_user_ty_72f5bb_idx'), models.Index(fields=['created_at'], name='users_dsr_u_created_192248_idx')],
            },
        ),
    ]
