# Generated by Django 5.2.13 on 2026-06-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dealer', '0002_dealerconfig_address_dealerconfig_business_name_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dsruser',
            options={'ordering': ['-created_at'], 'verbose_name': 'DSR User', 'verbose_name_plural': 'DSR Users'},
        ),
        migrations.AddField(
            model_name='dsruser',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available for work'), ('busy', 'Currently busy'), ('unavailable', 'Not available')], default='available', help_text='Availability status for freelance marketplace', max_length=20),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='avatar URL'),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short bio for public profile', verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications'),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily rate for freelance work', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Full display name', max_length=255, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for freelance work', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Profile visible in freelance marketplace'),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Phone number verified via OTP'),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='portfolio_url',
            field=models.URLField(blank=True, default='', help_text='External portfolio or LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from dealers (0.00-5.00)', max_digits=3),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text="List of skills: ['sales', 'inventory', 'collections']"),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='total_jobs',
            field=models.PositiveIntegerField(default=0, help_text='Total completed jobs/assignments'),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total reviews received'),
        ),
        migrations.AlterField(
            model_name='dsruser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email for notifications (optional)', max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='dsruser',
            name='phone',
            field=models.CharField(db_index=True, help_text='Primary identifier for login (required)', max_length=20, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='dsruser',
            name='user_type',
            field=models.CharField(choices=[('DSR', 'DSR'), ('Collector', 'Order Collector'), ('Manager', 'Manager'), ('ADMIN', 'Admin')], db_index=True, default='DSR', help_text='Type of user: DSR, Collector, Manager, or Admin', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dsruser',
            index=models.Index(fields=['phone'], name='users_dsr_u_phone_5d4a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='dsruser',
            index=models.Index(fields=['is_public', 'availability_status'], name='users_dsr_u_is_publ_82f33d_idx'),
        ),
    ]
