# Generated by Django 5.2.13 on 2026-06-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_dsruser_options_dsruser_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsruser',
            name='email',
            field=models.EmailField(db_index=True, help_text='Primary identifier for login (required)', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='dsruser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Phone number for contact (optional)', max_length=20, verbose_name='phone number'),
        ),
    ]
