# Generated by Django 5.2.13 on 2026-06-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_dsruser_email_alter_dsruser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsruser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
