# Generated by Django 5.2.13 on 2026-06-14 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dsruser_password_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DsrMarketplaceProfile',
            fields=[
                ('user', models.OneToOneField(help_text='The DSR user this marketplace profile belongs to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='marketplace_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_public', models.BooleanField(default=False, help_text='Profile visible in freelance marketplace')),
                ('availability_status', models.CharField(choices=[('available', 'Available for work'), ('busy', 'Currently busy'), ('unavailable', 'Not available')], default='available', help_text='Availability status for freelance marketplace', max_length=20)),
                ('skills', models.JSONField(blank=True, default=list, help_text="List of skills: ['sales', 'inventory', 'collections']")),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from dealers (0.00-5.00)', max_digits=3)),
                ('total_jobs', models.PositiveIntegerField(default=0, help_text='Total completed jobs/assignments')),
                ('total_reviews', models.PositiveIntegerField(default=0, help_text='Total reviews received')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for freelance work', max_digits=10, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Daily rate for freelance work', max_digits=10, null=True)),
                ('portfolio_url', models.URLField(blank=True, default='', help_text='External portfolio or LinkedIn URL')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='List of certifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DSR Marketplace Profile',
                'verbose_name_plural': 'DSR Marketplace Profiles',
                'db_table': 'users_dsr_marketplace_profile',
            },
        ),
        migrations.RemoveIndex(
            model_name='dsruser',
            name='users_dsr_u_is_publ_82f33d_idx',
        ),
        migrations.RemoveField(
            model_name='dsruser',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='dsruser',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='dsruser',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='dsruser',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='dsruser',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='dsruser',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='dsruser',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='dsruser',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='dsruser',
            name='selected_dealer',
        ),
        migrations.RemoveField(
            model_name='dsruser',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='dsruser',
            name='total_jobs',
        ),
        migrations.RemoveField(
            model_name='dsruser',
            name='total_reviews',
        ),
        migrations.AddField(
            model_name='dsruser',
            name='email_verification_expires',
            field=models.DateTimeField(blank=True, help_text='When the email verification token expires', null=True),
        ),
        migrations.AddField(
            model_name='dsruser',
            name='email_verification_token',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of the email verification token', max_length=64),
        ),
        migrations.AddIndex(
            model_name='dsrmarketplaceprofile',
            index=models.Index(fields=['is_public', 'availability_status'], name='users_dsr_m_is_publ_038d53_idx'),
        ),
    ]
