# Generated by Django 5.2.13 on 2026-04-25 11:48

import uuid
from django.db import migrations, models


# def gen_uuid(apps, schema_editor):
#     User = apps.get_model("users", "User")
#     for row in User.objects.all():
#         row.slug = uuid.uuid4()
#         row.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        # migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
