# Generated by Django 5.2.13 on 2026-04-26 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_otp_created_at_alter_otp_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_oauth_provider_uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oauth_provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oauth_uid',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
