# Generated by Django 5.2.13 on 2026-04-26 04:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangeToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique email change token (UUID4). Sent to current email.', unique=True)),
                ('new_email', models.EmailField(help_text='The pending new email address.', max_length=255, verbose_name='New Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Change Token',
                'verbose_name_plural': 'Email Change Tokens',
                'db_table': 'users_email_change_token',
                'ordering': ['-created_at'],
            },
        ),
    ]
