# Generated by Django 5.2.13 on 2026-04-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailChangeToken',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
