# Generated by Django 5.2.13 on 2026-06-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_currency_alter_user_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive failed login attempts. Reset on successful login.', verbose_name='Failed Login Attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='If set, account is temporarily locked until this time.', null=True, verbose_name='Locked Until'),
        ),
    ]
